void copyTreeSignal(int prod, int year) {
  // Example of Root macro to copy a subset of a Tree to a new Tree
  // One branch of the new Tree is written to a separate file
  // The input file has been generated by the program in $ROOTSYS/test/Event
  // with   Event 1000 1 1 1
  //Author: Rene Brun
    
  char oldProd[50];
  char newProd[50];
  char oldYear[50];
  char newYear[50];
  char puWeight[50];
  if (prod == 0){
    sprintf(oldProd,"ggH");
    sprintf(newProd,"gg");
  }else if (prod==1){
    sprintf(oldProd,"VBFH");
    sprintf(newProd,"vbf");
  }else if (prod==2){
    sprintf(oldProd,"WH");
    sprintf(newProd,"wh");
  }else if (prod==3){
    sprintf(oldProd,"ZH");
    sprintf(newProd,"zh");
  }else if (prod==4){
    sprintf(oldProd,"TTH");
    sprintf(newProd,"tth");
  }else{
    cout<< "arg1 must be 0, 1, 2, 3, or 4"<<endl;
    return;
  }

  if (year == 2011){
    sprintf(oldYear,"7TeV");
    sprintf(newYear,"2011");
    sprintf(puWeight,"puwei");
  }else if (year == 2012){
    sprintf(oldYear,"8TeV");
    sprintf(newYear,"2012");
    sprintf(puWeight,"puweiTrue");
  } else {
    cout << "arg2 must be 2011 or 2012"<<endl;
  }



  char oldFile[512];

  //Get old file, old tree and set top branch address

  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZeegamma_120_%s.root",oldYear,oldProd);
  TFile *old_el_file120 = new TFile(oldFile);
  TTree *old_el_tree120 = (TTree*)old_el_file120->Get("MCTree");
  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZeegamma_125_%s.root",oldYear,oldProd);
  TFile *old_el_file125 = new TFile(oldFile);
  TTree *old_el_tree125 = (TTree*)old_el_file125->Get("MCTree");
  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZeegamma_130_%s.root",oldYear,oldProd);
  TFile *old_el_file130 = new TFile(oldFile);
  TTree *old_el_tree130 = (TTree*)old_el_file130->Get("MCTree");
  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZeegamma_135_%s.root",oldYear,oldProd);
  TFile *old_el_file135 = new TFile(oldFile);
  TTree *old_el_tree135 = (TTree*)old_el_file135->Get("MCTree");
  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZeegamma_140_%s.root",oldYear,oldProd);
  TFile *old_el_file140 = new TFile(oldFile);
  TTree *old_el_tree140 = (TTree*)old_el_file140->Get("MCTree");
  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZeegamma_145_%s.root",oldYear,oldProd);
  TFile *old_el_file145 = new TFile(oldFile);
  TTree *old_el_tree145 = (TTree*)old_el_file145->Get("MCTree");
  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZeegamma_150_%s.root",oldYear,oldProd);
  TFile *old_el_file150 = new TFile(oldFile);
  TTree *old_el_tree150 = (TTree*)old_el_file150->Get("MCTree");
  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZeegamma_155_%s.root",oldYear,oldProd);
  TFile *old_el_file155 = new TFile(oldFile);
  TTree *old_el_tree155 = (TTree*)old_el_file155->Get("MCTree");
  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZeegamma_160_%s.root",oldYear,oldProd);
  TFile *old_el_file160 = new TFile(oldFile);
  TTree *old_el_tree160 = (TTree*)old_el_file160->Get("MCTree");

  double old_el_mass120,old_el_mass125,old_el_mass130,old_el_mass135,old_el_mass140,old_el_mass145,old_el_mass150,old_el_mass155,old_el_mass160;
  double old_el_weight120,old_el_weight125,old_el_weight130,old_el_weight135,old_el_weight140,old_el_weight145,old_el_weight150,old_el_weight155,old_el_weight160;
  double old_el_weightPU120,old_el_weightPU125,old_el_weightPU130,old_el_weightPU135,old_el_weightPU140,old_el_weightPU145,old_el_weightPU150,old_el_weightPU155,old_el_weightPU160;
  double old_el_lumi120,old_el_lumi125,old_el_lumi130,old_el_lumi135,old_el_lumi140,old_el_lumi145,old_el_lumi150,old_el_lumi155,old_el_lumi160;
  int old_el_nevt120,old_el_nevt125,old_el_nevt130,old_el_nevt135,old_el_nevt140,old_el_nevt145,old_el_nevt150,old_el_nevt155,old_el_nevt160;
  double old_el_cat120,old_el_cat125,old_el_cat130,old_el_cat135,old_el_cat140,old_el_cat145,old_el_cat150,old_el_cat155,old_el_cat160;
  double old_el_jet120,old_el_jet125,old_el_jet130,old_el_jet135,old_el_jet140,old_el_jet145,old_el_jet150,old_el_jet155,old_el_jet160;

  double new_el_mass120,new_el_mass125,new_el_mass130,new_el_mass135,new_el_mass140,new_el_mass145,new_el_mass150,new_el_mass155,new_el_mass160;
  double new_el_massCAT1120,new_el_massCAT1125,new_el_massCAT1130,new_el_massCAT1135,new_el_massCAT1140,new_el_massCAT1145,new_el_massCAT1150,new_el_massCAT1155,new_el_massCAT1160;
  double new_el_massCAT2120,new_el_massCAT2125,new_el_massCAT2130,new_el_massCAT2135,new_el_massCAT2140,new_el_massCAT2145,new_el_massCAT2150,new_el_massCAT2155,new_el_massCAT2160;
  double new_el_massCAT3120,new_el_massCAT3125,new_el_massCAT3130,new_el_massCAT3135,new_el_massCAT3140,new_el_massCAT3145,new_el_massCAT3150,new_el_massCAT3155,new_el_massCAT3160;
  double new_el_massCAT4120,new_el_massCAT4125,new_el_massCAT4130,new_el_massCAT4135,new_el_massCAT4140,new_el_massCAT4145,new_el_massCAT4150,new_el_massCAT4155,new_el_massCAT4160;
  double new_el_massCAT5120,new_el_massCAT5125,new_el_massCAT5130,new_el_massCAT5135,new_el_massCAT5140,new_el_massCAT5145,new_el_massCAT5150,new_el_massCAT5155,new_el_massCAT5160;
  double new_el_weight120,new_el_weight125,new_el_weight130,new_el_weight135,new_el_weight140,new_el_weight145,new_el_weight150,new_el_weight155,new_el_weight160;
  double new_el_lumi120,new_el_lumi125,new_el_lumi130,new_el_lumi135,new_el_lumi140,new_el_lumi145,new_el_lumi150,new_el_lumi155,new_el_lumi160;
  int new_el_nevt120,new_el_nevt125,new_el_nevt130,new_el_nevt135,new_el_nevt140,new_el_nevt145,new_el_nevt150,new_el_nevt155,new_el_nevt160;
  old_el_tree120->SetBranchAddress("mass",&old_el_mass120);
  old_el_tree125->SetBranchAddress("mass",&old_el_mass125);
  old_el_tree130->SetBranchAddress("mass",&old_el_mass130);
  old_el_tree135->SetBranchAddress("mass",&old_el_mass135);
  old_el_tree140->SetBranchAddress("mass",&old_el_mass140);
  old_el_tree145->SetBranchAddress("mass",&old_el_mass145);
  old_el_tree150->SetBranchAddress("mass",&old_el_mass150);
  old_el_tree155->SetBranchAddress("mass",&old_el_mass155);
  old_el_tree160->SetBranchAddress("mass",&old_el_mass160);

  old_el_tree120->SetBranchAddress("AllSF",&old_el_weight120);
  old_el_tree125->SetBranchAddress("AllSF",&old_el_weight125);
  old_el_tree130->SetBranchAddress("AllSF",&old_el_weight130);
  old_el_tree135->SetBranchAddress("AllSF",&old_el_weight135);
  old_el_tree140->SetBranchAddress("AllSF",&old_el_weight140);
  old_el_tree145->SetBranchAddress("AllSF",&old_el_weight145);
  old_el_tree150->SetBranchAddress("AllSF",&old_el_weight150);
  old_el_tree155->SetBranchAddress("AllSF",&old_el_weight155);
  old_el_tree160->SetBranchAddress("AllSF",&old_el_weight160);

  old_el_tree120->SetBranchAddress(puWeight,&old_el_weightPU120);
  old_el_tree125->SetBranchAddress(puWeight,&old_el_weightPU125);
  old_el_tree130->SetBranchAddress(puWeight,&old_el_weightPU130);
  old_el_tree135->SetBranchAddress(puWeight,&old_el_weightPU135);
  old_el_tree140->SetBranchAddress(puWeight,&old_el_weightPU140);
  old_el_tree145->SetBranchAddress(puWeight,&old_el_weightPU145);
  old_el_tree150->SetBranchAddress(puWeight,&old_el_weightPU150);
  old_el_tree155->SetBranchAddress(puWeight,&old_el_weightPU155);
  old_el_tree160->SetBranchAddress(puWeight,&old_el_weightPU160);

  old_el_tree120->SetBranchAddress("mcwei",&old_el_lumi120);
  old_el_tree125->SetBranchAddress("mcwei",&old_el_lumi125);
  old_el_tree130->SetBranchAddress("mcwei",&old_el_lumi130);
  old_el_tree135->SetBranchAddress("mcwei",&old_el_lumi135);
  old_el_tree140->SetBranchAddress("mcwei",&old_el_lumi140);
  old_el_tree145->SetBranchAddress("mcwei",&old_el_lumi145);
  old_el_tree150->SetBranchAddress("mcwei",&old_el_lumi150);
  old_el_tree155->SetBranchAddress("mcwei",&old_el_lumi155);
  old_el_tree160->SetBranchAddress("mcwei",&old_el_lumi160);

  old_el_tree120->SetBranchAddress("nevt",&old_el_nevt120);
  old_el_tree125->SetBranchAddress("nevt",&old_el_nevt125);
  old_el_tree130->SetBranchAddress("nevt",&old_el_nevt130);
  old_el_tree135->SetBranchAddress("nevt",&old_el_nevt135);
  old_el_tree140->SetBranchAddress("nevt",&old_el_nevt140);
  old_el_tree145->SetBranchAddress("nevt",&old_el_nevt145);
  old_el_tree150->SetBranchAddress("nevt",&old_el_nevt150);
  old_el_tree155->SetBranchAddress("nevt",&old_el_nevt155);
  old_el_tree160->SetBranchAddress("nevt",&old_el_nevt160);

  old_el_tree120->SetBranchAddress("cat1",&old_el_cat120);
  old_el_tree125->SetBranchAddress("cat1",&old_el_cat125);
  old_el_tree130->SetBranchAddress("cat1",&old_el_cat130);
  old_el_tree135->SetBranchAddress("cat1",&old_el_cat135);
  old_el_tree140->SetBranchAddress("cat1",&old_el_cat140);
  old_el_tree145->SetBranchAddress("cat1",&old_el_cat145);
  old_el_tree150->SetBranchAddress("cat1",&old_el_cat150);
  old_el_tree155->SetBranchAddress("cat1",&old_el_cat155);
  old_el_tree160->SetBranchAddress("cat1",&old_el_cat160);

  old_el_tree120->SetBranchAddress("jettag",&old_el_jet120);
  old_el_tree125->SetBranchAddress("jettag",&old_el_jet125);
  old_el_tree130->SetBranchAddress("jettag",&old_el_jet130);
  old_el_tree135->SetBranchAddress("jettag",&old_el_jet135);
  old_el_tree140->SetBranchAddress("jettag",&old_el_jet140);
  old_el_tree145->SetBranchAddress("jettag",&old_el_jet145);
  old_el_tree150->SetBranchAddress("jettag",&old_el_jet150);
  old_el_tree155->SetBranchAddress("jettag",&old_el_jet155);
  old_el_tree160->SetBranchAddress("jettag",&old_el_jet160);

  char newFile[512];
  sprintf(newFile,"allMass_%s_%s_eeg.root",newYear,newProd);
  TFile *new_el_file = new TFile(newFile,"recreate");

  char treeName[512], branch0[512], branch1[512], branch2[512], branch3[512], branch4[512], branch5[512], weightBranch[512], lumiBranch[512];

  sprintf(treeName,"m_llg_Signal%s%sM120",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM120",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM120",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM120",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM120",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM120",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM120",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM120",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM120",newYear,newProd);
  TTree *new_el_tree120 = new TTree(treeName,treeName);
  new_el_tree120->Branch(treeName,&new_el_mass120);
  new_el_tree120->Branch(branch1,&new_el_massCAT1120);
  new_el_tree120->Branch(branch2,&new_el_massCAT2120);
  new_el_tree120->Branch(branch3,&new_el_massCAT3120);
  new_el_tree120->Branch(branch4,&new_el_massCAT4120);
  new_el_tree120->Branch(branch5,&new_el_massCAT5120);
  new_el_tree120->Branch(weightBranch,&new_el_weight120);
  new_el_tree120->Branch(lumiBranch,&new_el_lumi120);
  sprintf(treeName,"m_llg_Signal%s%sM125",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM125",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM125",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM125",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM125",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM125",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM125",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM125",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM125",newYear,newProd);
  TTree *new_el_tree125 = new TTree(treeName,treeName);
  new_el_tree125->Branch(treeName,&new_el_mass125);
  new_el_tree125->Branch(branch1,&new_el_massCAT1125);
  new_el_tree125->Branch(branch2,&new_el_massCAT2125);
  new_el_tree125->Branch(branch3,&new_el_massCAT3125);
  new_el_tree125->Branch(branch4,&new_el_massCAT4125);
  new_el_tree125->Branch(branch5,&new_el_massCAT5125);
  new_el_tree125->Branch(weightBranch,&new_el_weight125);
  new_el_tree125->Branch(lumiBranch,&new_el_lumi125);
  sprintf(treeName,"m_llg_Signal%s%sM130",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM130",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM130",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM130",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM130",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM130",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM130",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM130",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM130",newYear,newProd);
  TTree *new_el_tree130 = new TTree(treeName,treeName);
  new_el_tree130->Branch(treeName,&new_el_mass130);
  new_el_tree130->Branch(branch1,&new_el_massCAT1130);
  new_el_tree130->Branch(branch2,&new_el_massCAT2130);
  new_el_tree130->Branch(branch3,&new_el_massCAT3130);
  new_el_tree130->Branch(branch4,&new_el_massCAT4130);
  new_el_tree130->Branch(branch5,&new_el_massCAT5130);
  new_el_tree130->Branch(weightBranch,&new_el_weight130);
  new_el_tree130->Branch(lumiBranch,&new_el_lumi130);
  sprintf(treeName,"m_llg_Signal%s%sM135",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM135",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM135",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM135",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM135",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM135",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM135",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM135",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM135",newYear,newProd);
  TTree *new_el_tree135 = new TTree(treeName,treeName);
  new_el_tree135->Branch(treeName,&new_el_mass135);
  new_el_tree135->Branch(branch1,&new_el_massCAT1135);
  new_el_tree135->Branch(branch2,&new_el_massCAT2135);
  new_el_tree135->Branch(branch3,&new_el_massCAT3135);
  new_el_tree135->Branch(branch4,&new_el_massCAT4135);
  new_el_tree135->Branch(branch5,&new_el_massCAT5135);
  new_el_tree135->Branch(weightBranch,&new_el_weight135);
  new_el_tree135->Branch(lumiBranch,&new_el_lumi135);
  sprintf(treeName,"m_llg_Signal%s%sM140",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM140",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM140",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM140",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM140",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM140",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM140",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM140",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM140",newYear,newProd);
  TTree *new_el_tree140 = new TTree(treeName,treeName);
  new_el_tree140->Branch(treeName,&new_el_mass140);
  new_el_tree140->Branch(branch1,&new_el_massCAT1140);
  new_el_tree140->Branch(branch2,&new_el_massCAT2140);
  new_el_tree140->Branch(branch3,&new_el_massCAT3140);
  new_el_tree140->Branch(branch4,&new_el_massCAT4140);
  new_el_tree140->Branch(branch5,&new_el_massCAT5140);
  new_el_tree140->Branch(weightBranch,&new_el_weight140);
  new_el_tree140->Branch(lumiBranch,&new_el_lumi140);
  sprintf(treeName,"m_llg_Signal%s%sM145",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM145",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM145",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM145",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM145",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM145",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM145",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM145",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM145",newYear,newProd);
  TTree *new_el_tree145 = new TTree(treeName,treeName);
  new_el_tree145->Branch(treeName,&new_el_mass145);
  new_el_tree145->Branch(branch1,&new_el_massCAT1145);
  new_el_tree145->Branch(branch2,&new_el_massCAT2145);
  new_el_tree145->Branch(branch3,&new_el_massCAT3145);
  new_el_tree145->Branch(branch4,&new_el_massCAT4145);
  new_el_tree145->Branch(branch5,&new_el_massCAT5145);
  new_el_tree145->Branch(weightBranch,&new_el_weight145);
  new_el_tree145->Branch(lumiBranch,&new_el_lumi145);
  sprintf(treeName,"m_llg_Signal%s%sM150",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM150",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM150",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM150",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM150",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM150",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM150",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM150",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM150",newYear,newProd);
  TTree *new_el_tree150 = new TTree(treeName,treeName);
  new_el_tree150->Branch(treeName,&new_el_mass150);
  new_el_tree150->Branch(branch1,&new_el_massCAT1150);
  new_el_tree150->Branch(branch2,&new_el_massCAT2150);
  new_el_tree150->Branch(branch3,&new_el_massCAT3150);
  new_el_tree150->Branch(branch4,&new_el_massCAT4150);
  new_el_tree150->Branch(branch5,&new_el_massCAT5150);
  new_el_tree150->Branch(weightBranch,&new_el_weight150);
  new_el_tree150->Branch(lumiBranch,&new_el_lumi150);
  sprintf(treeName,"m_llg_Signal%s%sM155",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM155",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM155",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM155",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM155",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM155",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM155",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM155",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM155",newYear,newProd);
  TTree *new_el_tree155 = new TTree(treeName,treeName);
  new_el_tree155->Branch(treeName,&new_el_mass155);
  new_el_tree155->Branch(branch1,&new_el_massCAT1155);
  new_el_tree155->Branch(branch2,&new_el_massCAT2155);
  new_el_tree155->Branch(branch3,&new_el_massCAT3155);
  new_el_tree155->Branch(branch4,&new_el_massCAT4155);
  new_el_tree155->Branch(branch5,&new_el_massCAT5155);
  new_el_tree155->Branch(weightBranch,&new_el_weight155);
  new_el_tree155->Branch(lumiBranch,&new_el_lumi155);
  sprintf(treeName,"m_llg_Signal%s%sM160",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM160",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM160",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM160",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM160",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM160",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM160",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM160",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM160",newYear,newProd);
  TTree *new_el_tree160 = new TTree(treeName,treeName);
  new_el_tree160->Branch(treeName,&new_el_mass160);
  new_el_tree160->Branch(branch1,&new_el_massCAT1160);
  new_el_tree160->Branch(branch2,&new_el_massCAT2160);
  new_el_tree160->Branch(branch3,&new_el_massCAT3160);
  new_el_tree160->Branch(branch4,&new_el_massCAT4160);
  new_el_tree160->Branch(branch5,&new_el_massCAT5160);
  new_el_tree160->Branch(weightBranch,&new_el_weight160);
  new_el_tree160->Branch(lumiBranch,&new_el_lumi160);

  for( int i=0; i<old_el_tree120->GetEntries(); i++ ) {
    new_el_mass120 = new_el_massCAT1120 = new_el_massCAT2120 = new_el_massCAT3120 = new_el_massCAT4120 = new_el_massCAT5120 = -1;
    old_el_tree120->GetEntry(i);
    new_el_mass120 = old_el_mass120;
    new_el_weight120 = old_el_weight120*old_el_weightPU120;
    new_el_lumi120 = old_el_nevt120;
    if (old_el_cat120 == 11 && old_el_jet120 == -1){
      new_el_massCAT1120 = old_el_mass120;
    }else if (old_el_cat120 == 12 && old_el_jet120 == -1){
      new_el_massCAT4120 = old_el_mass120;
    }else if ((old_el_cat120 == 15 || old_el_cat120 == 16) && old_el_jet120 == -1){
      new_el_massCAT3120 = old_el_mass120;
    }else if ((old_el_cat120 == 13 || old_el_cat120 == 14) && old_el_jet120 == -1){
      new_el_massCAT2120 = old_el_mass120;
    }else if (old_el_jet120 == 1){
      new_el_massCAT5120 = old_el_mass120;
    }

    new_el_tree120->Fill();
  }

  for( int i=0; i<old_el_tree125->GetEntries(); i++ ) {
    new_el_mass125 = new_el_massCAT1125 = new_el_massCAT2125 = new_el_massCAT3125 = new_el_massCAT4125 = new_el_massCAT5125 = -1;
    old_el_tree125->GetEntry(i);
    new_el_mass125 = old_el_mass125;
    new_el_weight125 = old_el_weight125*old_el_weightPU125;
    new_el_lumi125 = old_el_nevt125;
    if (old_el_cat125 == 11 && old_el_jet125 == -1){
      new_el_massCAT1125 = old_el_mass125;
    }else if (old_el_cat125 == 12 && old_el_jet125 == -1){
      new_el_massCAT4125 = old_el_mass125;
    }else if ((old_el_cat125 == 15 || old_el_cat125 == 16) && old_el_jet125 == -1){
      new_el_massCAT3125 = old_el_mass125;
    }else if ((old_el_cat125 == 13 || old_el_cat125 == 14) && old_el_jet125 == -1){
      new_el_massCAT2125 = old_el_mass125;
    }else if (old_el_jet125 == 1){
      new_el_massCAT5125 = old_el_mass125;
    }

    new_el_tree125->Fill();
  }

  for( int i=0; i<old_el_tree130->GetEntries(); i++ ) {
    new_el_mass130 = new_el_massCAT1130 = new_el_massCAT2130 = new_el_massCAT3130 = new_el_massCAT4130 = new_el_massCAT5130 = -1;
    old_el_tree130->GetEntry(i);
    new_el_mass130 = old_el_mass130;
    new_el_weight130 = old_el_weight130*old_el_weightPU130;
    new_el_lumi130 = old_el_nevt130;
    if (old_el_cat130 == 11 && old_el_jet130 == -1){
      new_el_massCAT1130 = old_el_mass130;
    }else if (old_el_cat130 == 12 && old_el_jet130 == -1){
      new_el_massCAT4130 = old_el_mass130;
    }else if ((old_el_cat130 == 15 || old_el_cat130 == 16) && old_el_jet130 == -1){
      new_el_massCAT3130 = old_el_mass130;
    }else if ((old_el_cat130 == 13 || old_el_cat130 == 14) && old_el_jet130 == -1){
      new_el_massCAT2130 = old_el_mass130;
    }else if (old_el_jet130 == 1){
      new_el_massCAT5130 = old_el_mass130;
    }

    new_el_tree130->Fill();
  }

  for( int i=0; i<old_el_tree135->GetEntries(); i++ ) {
    new_el_mass135 = new_el_massCAT1135 = new_el_massCAT2135 = new_el_massCAT3135 = new_el_massCAT4135 = new_el_massCAT5135 = -1;
    old_el_tree135->GetEntry(i);
    new_el_mass135 = old_el_mass135;
    new_el_weight135 = old_el_weight135*old_el_weightPU135;
    new_el_lumi135 = old_el_nevt135;
    if (old_el_cat135 == 11 && old_el_jet135 == -1){
      new_el_massCAT1135 = old_el_mass135;
    }else if (old_el_cat135 == 12 && old_el_jet135 == -1){
      new_el_massCAT4135 = old_el_mass135;
    }else if ((old_el_cat135 == 15 || old_el_cat135 == 16) && old_el_jet135 == -1){
      new_el_massCAT3135 = old_el_mass135;
    }else if ((old_el_cat135 == 13 || old_el_cat135 == 14) && old_el_jet135 == -1){
      new_el_massCAT2135 = old_el_mass135;
    }else if (old_el_jet135 == 1){
      new_el_massCAT5135 = old_el_mass135;
    }

    new_el_tree135->Fill();
  }
  
  for( int i=0; i<old_el_tree140->GetEntries(); i++ ) {
    new_el_mass140 = new_el_massCAT1140 = new_el_massCAT2140 = new_el_massCAT3140 = new_el_massCAT4140 = new_el_massCAT5140 = -1;
    old_el_tree140->GetEntry(i);
    new_el_mass140 = old_el_mass140;
    new_el_weight140 = old_el_weight140*old_el_weightPU140;
    new_el_lumi140 = old_el_nevt140;
    if (old_el_cat140 == 11 && old_el_jet140 == -1){
      new_el_massCAT1140 = old_el_mass140;
    }else if (old_el_cat140 == 12 && old_el_jet140 == -1){
      new_el_massCAT4140 = old_el_mass140;
    }else if ((old_el_cat140 == 15 || old_el_cat140 == 16) && old_el_jet140 == -1){
      new_el_massCAT3140 = old_el_mass140;
    }else if ((old_el_cat140 == 13 || old_el_cat140 == 14) && old_el_jet140 == -1){
      new_el_massCAT2140 = old_el_mass140;
    }else if (old_el_jet140 == 1){
      new_el_massCAT5140 = old_el_mass140;
    }

    new_el_tree140->Fill();
  }

  for( int i=0; i<old_el_tree145->GetEntries(); i++ ) {
    new_el_mass145 = new_el_massCAT1145 = new_el_massCAT2145 = new_el_massCAT3145 = new_el_massCAT4145 = new_el_massCAT5145 = -1;
    old_el_tree145->GetEntry(i);
    new_el_mass145 = old_el_mass145;
    new_el_weight145 = old_el_weight145*old_el_weightPU145;
    new_el_lumi145 = old_el_nevt145;
    if (old_el_cat145 == 11 && old_el_jet145 == -1){
      new_el_massCAT1145 = old_el_mass145;
    }else if (old_el_cat145 == 12 && old_el_jet145 == -1){
      new_el_massCAT4145 = old_el_mass145;
    }else if ((old_el_cat145 == 15 || old_el_cat145 == 16) && old_el_jet145 == -1){
      new_el_massCAT3145 = old_el_mass145;
    }else if ((old_el_cat145 == 13 || old_el_cat145 == 14) && old_el_jet145 == -1){
      new_el_massCAT2145 = old_el_mass145;
    }else if (old_el_jet145 == 1){
      new_el_massCAT5145 = old_el_mass145;
    }

    new_el_tree145->Fill();
  }

  for( int i=0; i<old_el_tree150->GetEntries(); i++ ) {
    new_el_mass150 = new_el_massCAT1150 = new_el_massCAT2150 = new_el_massCAT3150 = new_el_massCAT4150 = new_el_massCAT5150 = -1;
    old_el_tree150->GetEntry(i);
    new_el_mass150 = old_el_mass150;
    new_el_weight150 = old_el_weight150*old_el_weightPU150;
    new_el_lumi150 = old_el_nevt150;
    if (old_el_cat150 == 11 && old_el_jet150 == -1){
      new_el_massCAT1150 = old_el_mass150;
    }else if (old_el_cat150 == 12 && old_el_jet150 == -1){
      new_el_massCAT4150 = old_el_mass150;
    }else if ((old_el_cat150 == 15 || old_el_cat150 == 16) && old_el_jet150 == -1){
      new_el_massCAT3150 = old_el_mass150;
    }else if ((old_el_cat150 == 13 || old_el_cat150 == 14) && old_el_jet150 == -1){
      new_el_massCAT2150 = old_el_mass150;
    }else if (old_el_jet150 == 1){
      new_el_massCAT5150 = old_el_mass150;
    }

    new_el_tree150->Fill();
  }

  for( int i=0; i<old_el_tree155->GetEntries(); i++ ) {
    new_el_mass155 = new_el_massCAT1155 = new_el_massCAT2155 = new_el_massCAT3155 = new_el_massCAT4155 = new_el_massCAT5155 = -1;
    old_el_tree155->GetEntry(i);
    new_el_mass155 = old_el_mass155;
    new_el_weight155 = old_el_weight155*old_el_weightPU155;
    new_el_lumi155 = old_el_nevt155;
    if (old_el_cat155 == 11 && old_el_jet155 == -1){
      new_el_massCAT1155 = old_el_mass155;
    }else if (old_el_cat155 == 12 && old_el_jet155 == -1){
      new_el_massCAT4155 = old_el_mass155;
    }else if ((old_el_cat155 == 15 || old_el_cat155 == 16) && old_el_jet155 == -1){
      new_el_massCAT3155 = old_el_mass155;
    }else if ((old_el_cat155 == 13 || old_el_cat155 == 14) && old_el_jet155 == -1){
      new_el_massCAT2155 = old_el_mass155;
    }else if (old_el_jet155 == 1){
      new_el_massCAT5155 = old_el_mass155;
    }

    new_el_tree155->Fill();
  }

  for( int i=0; i<old_el_tree160->GetEntries(); i++ ) {
    new_el_mass160 = new_el_massCAT1160 = new_el_massCAT2160 = new_el_massCAT3160 = new_el_massCAT4160 = new_el_massCAT5160 = -1;
    old_el_tree160->GetEntry(i);
    new_el_mass160 = old_el_mass160;
    new_el_weight160 = old_el_weight160*old_el_weightPU160;
    new_el_lumi160 = old_el_nevt160;
    if (old_el_cat160 == 11 && old_el_jet160 == -1){
      new_el_massCAT1160 = old_el_mass160;
    }else if (old_el_cat160 == 12 && old_el_jet160 == -1){
      new_el_massCAT4160 = old_el_mass160;
    }else if ((old_el_cat160 == 15 || old_el_cat160 == 16) && old_el_jet160 == -1){
      new_el_massCAT3160 = old_el_mass160;
    }else if ((old_el_cat160 == 13 || old_el_cat160 == 14) && old_el_jet160 == -1){
      new_el_massCAT2160 = old_el_mass160;
    }else if (old_el_jet160 == 1){
      new_el_massCAT5160 = old_el_mass160;
    }

    new_el_tree160->Fill();
  }


  new_el_tree120->Print();
  new_el_tree125->Print();
  new_el_tree130->Print();
  new_el_tree135->Print();
  new_el_tree140->Print();
  new_el_tree145->Print();
  new_el_tree150->Print();
  new_el_tree155->Print();
  new_el_tree160->Print();
  new_el_file->Write();
  delete old_el_file120;
  delete old_el_file125;
  delete old_el_file130;
  delete old_el_file135;
  delete old_el_file140;
  delete old_el_file145;
  delete old_el_file150;
  delete old_el_file155;
  delete old_el_file160;
  delete new_el_file;

  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZmumugamma_120_%s.root",oldYear,oldProd);
  TFile *old_mu_file120 = new TFile(oldFile);
  TTree *old_mu_tree120 = (TTree*)old_mu_file120->Get("MCTree");
  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZmumugamma_125_%s.root",oldYear,oldProd);
  TFile *old_mu_file125 = new TFile(oldFile);
  TTree *old_mu_tree125 = (TTree*)old_mu_file125->Get("MCTree");
  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZmumugamma_130_%s.root",oldYear,oldProd);
  TFile *old_mu_file130 = new TFile(oldFile);
  TTree *old_mu_tree130 = (TTree*)old_mu_file130->Get("MCTree");
  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZmumugamma_135_%s.root",oldYear,oldProd);
  TFile *old_mu_file135 = new TFile(oldFile);
  TTree *old_mu_tree135 = (TTree*)old_mu_file135->Get("MCTree");
  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZmumugamma_140_%s.root",oldYear,oldProd);
  TFile *old_mu_file140 = new TFile(oldFile);
  TTree *old_mu_tree140 = (TTree*)old_mu_file140->Get("MCTree");
  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZmumugamma_145_%s.root",oldYear,oldProd);
  TFile *old_mu_file145 = new TFile(oldFile);
  TTree *old_mu_tree145 = (TTree*)old_mu_file145->Get("MCTree");
  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZmumugamma_150_%s.root",oldYear,oldProd);
  TFile *old_mu_file150 = new TFile(oldFile);
  TTree *old_mu_tree150 = (TTree*)old_mu_file150->Get("MCTree");
  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZmumugamma_155_%s.root",oldYear,oldProd);
  TFile *old_mu_file155 = new TFile(oldFile);
  TTree *old_mu_tree155 = (TTree*)old_mu_file155->Get("MCTree");
  sprintf(oldFile, "poterSource/%s_Sig/HiggsToZmumugamma_160_%s.root",oldYear,oldProd);
  TFile *old_mu_file160 = new TFile(oldFile);
  TTree *old_mu_tree160 = (TTree*)old_mu_file160->Get("MCTree");

  double old_mu_mass120,old_mu_mass125,old_mu_mass130,old_mu_mass135,old_mu_mass140,old_mu_mass145,old_mu_mass150,old_mu_mass155,old_mu_mass160;
  double old_mu_weight120,old_mu_weight125,old_mu_weight130,old_mu_weight135,old_mu_weight140,old_mu_weight145,old_mu_weight150,old_mu_weight155,old_mu_weight160;
  double old_mu_weightPU120,old_mu_weightPU125,old_mu_weightPU130,old_mu_weightPU135,old_mu_weightPU140,old_mu_weightPU145,old_mu_weightPU150,old_mu_weightPU155,old_mu_weightPU160;
  double old_mu_lumi120,old_mu_lumi125,old_mu_lumi130,old_mu_lumi135,old_mu_lumi140,old_mu_lumi145,old_mu_lumi150,old_mu_lumi155,old_mu_lumi160;
  int old_mu_nevt120,old_mu_nevt125,old_mu_nevt130,old_mu_nevt135,old_mu_nevt140,old_mu_nevt145,old_mu_nevt150,old_mu_nevt155,old_mu_nevt160;
  double old_mu_cat120,old_mu_cat125,old_mu_cat130,old_mu_cat135,old_mu_cat140,old_mu_cat145,old_mu_cat150,old_mu_cat155,old_mu_cat160;
  double old_mu_jet120,old_mu_jet125,old_mu_jet130,old_mu_jet135,old_mu_jet140,old_mu_jet145,old_mu_jet150,old_mu_jet155,old_mu_jet160;

  double new_mu_mass120,new_mu_mass125,new_mu_mass130,new_mu_mass135,new_mu_mass140,new_mu_mass145,new_mu_mass150,new_mu_mass155,new_mu_mass160;
  double new_mu_massCAT1120,new_mu_massCAT1125,new_mu_massCAT1130,new_mu_massCAT1135,new_mu_massCAT1140,new_mu_massCAT1145,new_mu_massCAT1150,new_mu_massCAT1155,new_mu_massCAT1160;
  double new_mu_massCAT2120,new_mu_massCAT2125,new_mu_massCAT2130,new_mu_massCAT2135,new_mu_massCAT2140,new_mu_massCAT2145,new_mu_massCAT2150,new_mu_massCAT2155,new_mu_massCAT2160;
  double new_mu_massCAT3120,new_mu_massCAT3125,new_mu_massCAT3130,new_mu_massCAT3135,new_mu_massCAT3140,new_mu_massCAT3145,new_mu_massCAT3150,new_mu_massCAT3155,new_mu_massCAT3160;
  double new_mu_massCAT4120,new_mu_massCAT4125,new_mu_massCAT4130,new_mu_massCAT4135,new_mu_massCAT4140,new_mu_massCAT4145,new_mu_massCAT4150,new_mu_massCAT4155,new_mu_massCAT4160;
  double new_mu_massCAT5120,new_mu_massCAT5125,new_mu_massCAT5130,new_mu_massCAT5135,new_mu_massCAT5140,new_mu_massCAT5145,new_mu_massCAT5150,new_mu_massCAT5155,new_mu_massCAT5160;
  double new_mu_weight120,new_mu_weight125,new_mu_weight130,new_mu_weight135,new_mu_weight140,new_mu_weight145,new_mu_weight150,new_mu_weight155,new_mu_weight160;
  double new_mu_lumi120,new_mu_lumi125,new_mu_lumi130,new_mu_lumi135,new_mu_lumi140,new_mu_lumi145,new_mu_lumi150,new_mu_lumi155,new_mu_lumi160;
  int new_mu_nevt120,new_mu_nevt125,new_mu_nevt130,new_mu_nevt135,new_mu_nevt140,new_mu_nevt145,new_mu_nevt150,new_mu_nevt155,new_mu_nevt160;
  old_mu_tree120->SetBranchAddress("mass",&old_mu_mass120);
  old_mu_tree125->SetBranchAddress("mass",&old_mu_mass125);
  old_mu_tree130->SetBranchAddress("mass",&old_mu_mass130);
  old_mu_tree135->SetBranchAddress("mass",&old_mu_mass135);
  old_mu_tree140->SetBranchAddress("mass",&old_mu_mass140);
  old_mu_tree145->SetBranchAddress("mass",&old_mu_mass145);
  old_mu_tree150->SetBranchAddress("mass",&old_mu_mass150);
  old_mu_tree155->SetBranchAddress("mass",&old_mu_mass155);
  old_mu_tree160->SetBranchAddress("mass",&old_mu_mass160);

  old_mu_tree120->SetBranchAddress("AllSF",&old_mu_weight120);
  old_mu_tree125->SetBranchAddress("AllSF",&old_mu_weight125);
  old_mu_tree130->SetBranchAddress("AllSF",&old_mu_weight130);
  old_mu_tree135->SetBranchAddress("AllSF",&old_mu_weight135);
  old_mu_tree140->SetBranchAddress("AllSF",&old_mu_weight140);
  old_mu_tree145->SetBranchAddress("AllSF",&old_mu_weight145);
  old_mu_tree150->SetBranchAddress("AllSF",&old_mu_weight150);
  old_mu_tree155->SetBranchAddress("AllSF",&old_mu_weight155);
  old_mu_tree160->SetBranchAddress("AllSF",&old_mu_weight160);

  old_mu_tree120->SetBranchAddress(puWeight,&old_mu_weightPU120);
  old_mu_tree125->SetBranchAddress(puWeight,&old_mu_weightPU125);
  old_mu_tree130->SetBranchAddress(puWeight,&old_mu_weightPU130);
  old_mu_tree135->SetBranchAddress(puWeight,&old_mu_weightPU135);
  old_mu_tree140->SetBranchAddress(puWeight,&old_mu_weightPU140);
  old_mu_tree145->SetBranchAddress(puWeight,&old_mu_weightPU145);
  old_mu_tree150->SetBranchAddress(puWeight,&old_mu_weightPU150);
  old_mu_tree155->SetBranchAddress(puWeight,&old_mu_weightPU155);
  old_mu_tree160->SetBranchAddress(puWeight,&old_mu_weightPU160);

  old_mu_tree120->SetBranchAddress("mcwei",&old_mu_lumi120);
  old_mu_tree125->SetBranchAddress("mcwei",&old_mu_lumi125);
  old_mu_tree130->SetBranchAddress("mcwei",&old_mu_lumi130);
  old_mu_tree135->SetBranchAddress("mcwei",&old_mu_lumi135);
  old_mu_tree140->SetBranchAddress("mcwei",&old_mu_lumi140);
  old_mu_tree145->SetBranchAddress("mcwei",&old_mu_lumi145);
  old_mu_tree150->SetBranchAddress("mcwei",&old_mu_lumi150);
  old_mu_tree155->SetBranchAddress("mcwei",&old_mu_lumi155);
  old_mu_tree160->SetBranchAddress("mcwei",&old_mu_lumi160);

  old_mu_tree120->SetBranchAddress("nevt",&old_mu_nevt120);
  old_mu_tree125->SetBranchAddress("nevt",&old_mu_nevt125);
  old_mu_tree130->SetBranchAddress("nevt",&old_mu_nevt130);
  old_mu_tree135->SetBranchAddress("nevt",&old_mu_nevt135);
  old_mu_tree140->SetBranchAddress("nevt",&old_mu_nevt140);
  old_mu_tree145->SetBranchAddress("nevt",&old_mu_nevt145);
  old_mu_tree150->SetBranchAddress("nevt",&old_mu_nevt150);
  old_mu_tree155->SetBranchAddress("nevt",&old_mu_nevt155);
  old_mu_tree160->SetBranchAddress("nevt",&old_mu_nevt160);

  old_mu_tree120->SetBranchAddress("cat1",&old_mu_cat120);
  old_mu_tree125->SetBranchAddress("cat1",&old_mu_cat125);
  old_mu_tree130->SetBranchAddress("cat1",&old_mu_cat130);
  old_mu_tree135->SetBranchAddress("cat1",&old_mu_cat135);
  old_mu_tree140->SetBranchAddress("cat1",&old_mu_cat140);
  old_mu_tree145->SetBranchAddress("cat1",&old_mu_cat145);
  old_mu_tree150->SetBranchAddress("cat1",&old_mu_cat150);
  old_mu_tree155->SetBranchAddress("cat1",&old_mu_cat155);
  old_mu_tree160->SetBranchAddress("cat1",&old_mu_cat160);

  old_mu_tree120->SetBranchAddress("jettag",&old_mu_jet120);
  old_mu_tree125->SetBranchAddress("jettag",&old_mu_jet125);
  old_mu_tree130->SetBranchAddress("jettag",&old_mu_jet130);
  old_mu_tree135->SetBranchAddress("jettag",&old_mu_jet135);
  old_mu_tree140->SetBranchAddress("jettag",&old_mu_jet140);
  old_mu_tree145->SetBranchAddress("jettag",&old_mu_jet145);
  old_mu_tree150->SetBranchAddress("jettag",&old_mu_jet150);
  old_mu_tree155->SetBranchAddress("jettag",&old_mu_jet155);
  old_mu_tree160->SetBranchAddress("jettag",&old_mu_jet160);

  sprintf(newFile,"allMass_%s_%s_mumug.root",newYear,newProd);
  TFile *new_mu_file = new TFile(newFile,"recreate");

  sprintf(treeName,"m_llg_Signal%s%sM120",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM120",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM120",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM120",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM120",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM120",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM120",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM120",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM120",newYear,newProd);
  TTree *new_mu_tree120 = new TTree(treeName,treeName);
  new_mu_tree120->Branch(treeName,&new_mu_mass120);
  new_mu_tree120->Branch(branch1,&new_mu_massCAT1120);
  new_mu_tree120->Branch(branch2,&new_mu_massCAT2120);
  new_mu_tree120->Branch(branch3,&new_mu_massCAT3120);
  new_mu_tree120->Branch(branch4,&new_mu_massCAT4120);
  new_mu_tree120->Branch(branch5,&new_mu_massCAT5120);
  new_mu_tree120->Branch(weightBranch,&new_mu_weight120);
  new_mu_tree120->Branch(lumiBranch,&new_mu_lumi120);
  sprintf(treeName,"m_llg_Signal%s%sM125",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM125",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM125",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM125",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM125",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM125",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM125",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM125",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM125",newYear,newProd);
  TTree *new_mu_tree125 = new TTree(treeName,treeName);
  new_mu_tree125->Branch(treeName,&new_mu_mass125);
  new_mu_tree125->Branch(branch1,&new_mu_massCAT1125);
  new_mu_tree125->Branch(branch2,&new_mu_massCAT2125);
  new_mu_tree125->Branch(branch3,&new_mu_massCAT3125);
  new_mu_tree125->Branch(branch4,&new_mu_massCAT4125);
  new_mu_tree125->Branch(branch5,&new_mu_massCAT5125);
  new_mu_tree125->Branch(weightBranch,&new_mu_weight125);
  new_mu_tree125->Branch(lumiBranch,&new_mu_lumi125);
  sprintf(treeName,"m_llg_Signal%s%sM130",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM130",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM130",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM130",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM130",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM130",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM130",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM130",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM130",newYear,newProd);
  TTree *new_mu_tree130 = new TTree(treeName,treeName);
  new_mu_tree130->Branch(treeName,&new_mu_mass130);
  new_mu_tree130->Branch(branch1,&new_mu_massCAT1130);
  new_mu_tree130->Branch(branch2,&new_mu_massCAT2130);
  new_mu_tree130->Branch(branch3,&new_mu_massCAT3130);
  new_mu_tree130->Branch(branch4,&new_mu_massCAT4130);
  new_mu_tree130->Branch(branch5,&new_mu_massCAT5130);
  new_mu_tree130->Branch(weightBranch,&new_mu_weight130);
  new_mu_tree130->Branch(lumiBranch,&new_mu_lumi130);
  sprintf(treeName,"m_llg_Signal%s%sM135",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM135",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM135",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM135",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM135",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM135",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM135",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM135",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM135",newYear,newProd);
  TTree *new_mu_tree135 = new TTree(treeName,treeName);
  new_mu_tree135->Branch(treeName,&new_mu_mass135);
  new_mu_tree135->Branch(branch1,&new_mu_massCAT1135);
  new_mu_tree135->Branch(branch2,&new_mu_massCAT2135);
  new_mu_tree135->Branch(branch3,&new_mu_massCAT3135);
  new_mu_tree135->Branch(branch4,&new_mu_massCAT4135);
  new_mu_tree135->Branch(branch5,&new_mu_massCAT5135);
  new_mu_tree135->Branch(weightBranch,&new_mu_weight135);
  new_mu_tree135->Branch(lumiBranch,&new_mu_lumi135);
  sprintf(treeName,"m_llg_Signal%s%sM140",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM140",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM140",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM140",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM140",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM140",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM140",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM140",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM140",newYear,newProd);
  TTree *new_mu_tree140 = new TTree(treeName,treeName);
  new_mu_tree140->Branch(treeName,&new_mu_mass140);
  new_mu_tree140->Branch(branch1,&new_mu_massCAT1140);
  new_mu_tree140->Branch(branch2,&new_mu_massCAT2140);
  new_mu_tree140->Branch(branch3,&new_mu_massCAT3140);
  new_mu_tree140->Branch(branch4,&new_mu_massCAT4140);
  new_mu_tree140->Branch(branch5,&new_mu_massCAT5140);
  new_mu_tree140->Branch(weightBranch,&new_mu_weight140);
  new_mu_tree140->Branch(lumiBranch,&new_mu_lumi140);
  sprintf(treeName,"m_llg_Signal%s%sM145",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM145",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM145",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM145",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM145",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM145",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM145",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM145",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM145",newYear,newProd);
  TTree *new_mu_tree145 = new TTree(treeName,treeName);
  new_mu_tree145->Branch(treeName,&new_mu_mass145);
  new_mu_tree145->Branch(branch1,&new_mu_massCAT1145);
  new_mu_tree145->Branch(branch2,&new_mu_massCAT2145);
  new_mu_tree145->Branch(branch3,&new_mu_massCAT3145);
  new_mu_tree145->Branch(branch4,&new_mu_massCAT4145);
  new_mu_tree145->Branch(branch5,&new_mu_massCAT5145);
  new_mu_tree145->Branch(weightBranch,&new_mu_weight145);
  new_mu_tree145->Branch(lumiBranch,&new_mu_lumi145);
  sprintf(treeName,"m_llg_Signal%s%sM150",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM150",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM150",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM150",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM150",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM150",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM150",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM150",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM150",newYear,newProd);
  TTree *new_mu_tree150 = new TTree(treeName,treeName);
  new_mu_tree150->Branch(treeName,&new_mu_mass150);
  new_mu_tree150->Branch(branch1,&new_mu_massCAT1150);
  new_mu_tree150->Branch(branch2,&new_mu_massCAT2150);
  new_mu_tree150->Branch(branch3,&new_mu_massCAT3150);
  new_mu_tree150->Branch(branch4,&new_mu_massCAT4150);
  new_mu_tree150->Branch(branch5,&new_mu_massCAT5150);
  new_mu_tree150->Branch(weightBranch,&new_mu_weight150);
  new_mu_tree150->Branch(lumiBranch,&new_mu_lumi150);
  sprintf(treeName,"m_llg_Signal%s%sM155",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM155",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM155",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM155",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM155",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM155",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM155",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM155",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM155",newYear,newProd);
  TTree *new_mu_tree155 = new TTree(treeName,treeName);
  new_mu_tree155->Branch(treeName,&new_mu_mass155);
  new_mu_tree155->Branch(branch1,&new_mu_massCAT1155);
  new_mu_tree155->Branch(branch2,&new_mu_massCAT2155);
  new_mu_tree155->Branch(branch3,&new_mu_massCAT3155);
  new_mu_tree155->Branch(branch4,&new_mu_massCAT4155);
  new_mu_tree155->Branch(branch5,&new_mu_massCAT5155);
  new_mu_tree155->Branch(weightBranch,&new_mu_weight155);
  new_mu_tree155->Branch(lumiBranch,&new_mu_lumi155);
  sprintf(treeName,"m_llg_Signal%s%sM160",newYear,newProd);
  sprintf(branch0,"m_llg_Signal%s%sM160",newYear,newProd);
  sprintf(branch1,"m_llgCAT1_Signal%s%sM160",newYear,newProd);
  sprintf(branch2,"m_llgCAT2_Signal%s%sM160",newYear,newProd);
  sprintf(branch3,"m_llgCAT3_Signal%s%sM160",newYear,newProd);
  sprintf(branch4,"m_llgCAT4_Signal%s%sM160",newYear,newProd);
  sprintf(branch5,"m_llgCAT5_Signal%s%sM160",newYear,newProd);
  sprintf(weightBranch,"unBinnedWeight_Signal%s%sM160",newYear,newProd);
  sprintf(lumiBranch,"unBinnedLumiXS_Signal%s%sM160",newYear,newProd);
  TTree *new_mu_tree160 = new TTree(treeName,treeName);
  new_mu_tree160->Branch(treeName,&new_mu_mass160);
  new_mu_tree160->Branch(branch1,&new_mu_massCAT1160);
  new_mu_tree160->Branch(branch2,&new_mu_massCAT2160);
  new_mu_tree160->Branch(branch3,&new_mu_massCAT3160);
  new_mu_tree160->Branch(branch4,&new_mu_massCAT4160);
  new_mu_tree160->Branch(branch5,&new_mu_massCAT5160);
  new_mu_tree160->Branch(weightBranch,&new_mu_weight160);
  new_mu_tree160->Branch(lumiBranch,&new_mu_lumi160);

  for( int i=0; i<old_mu_tree120->GetEntries(); i++ ) {
    new_mu_mass120 = new_mu_massCAT1120 = new_mu_massCAT2120 = new_mu_massCAT3120 = new_mu_massCAT4120 = new_mu_massCAT5120 = -1;
    old_mu_tree120->GetEntry(i);
    new_mu_mass120 = old_mu_mass120;
    new_mu_weight120 = old_mu_weight120*old_mu_weightPU120;
    new_mu_lumi120 = old_mu_nevt120;
    if (old_mu_cat120 == 21 && old_mu_jet120 == -1){
      new_mu_massCAT1120 = old_mu_mass120;
    }else if (old_mu_cat120 == 22 && old_mu_jet120 == -1){
      new_mu_massCAT4120 = old_mu_mass120;
    }else if ((old_mu_cat120 == 23 || old_mu_cat120 == 24) && old_mu_jet120 == -1){
      new_mu_massCAT3120 = old_mu_mass120;
    }else if ((old_mu_cat120 == 25 || old_mu_cat120 == 26) && old_mu_jet120 == -1){
      new_mu_massCAT2120 = old_mu_mass120;
    }else if (old_mu_jet120 == 1){
      new_mu_massCAT5120 = old_mu_mass120;
    }

    new_mu_tree120->Fill();
  }

  for( int i=0; i<old_mu_tree125->GetEntries(); i++ ) {
    new_mu_mass125 = new_mu_massCAT1125 = new_mu_massCAT2125 = new_mu_massCAT3125 = new_mu_massCAT4125 = new_mu_massCAT5125 = -1;
    old_mu_tree125->GetEntry(i);
    new_mu_mass125 = old_mu_mass125;
    new_mu_weight125 = old_mu_weight125*old_mu_weightPU125;
    new_mu_lumi125 = old_mu_nevt125;
    if (old_mu_cat125 == 21 && old_mu_jet125 == -1){
      new_mu_massCAT1125 = old_mu_mass125;
    }else if (old_mu_cat125 == 22 && old_mu_jet125 == -1){
      new_mu_massCAT4125 = old_mu_mass125;
    }else if ((old_mu_cat125 == 23 || old_mu_cat125 == 24) && old_mu_jet125 == -1){
      new_mu_massCAT3125 = old_mu_mass125;
    }else if ((old_mu_cat125 == 25 || old_mu_cat125 == 26) && old_mu_jet125 == -1){
      new_mu_massCAT2125 = old_mu_mass125;
    }else if (old_mu_jet125 == 1){
      new_mu_massCAT5125 = old_mu_mass125;
    }

    new_mu_tree125->Fill();
  }

  for( int i=0; i<old_mu_tree130->GetEntries(); i++ ) {
    new_mu_mass130 = new_mu_massCAT1130 = new_mu_massCAT2130 = new_mu_massCAT3130 = new_mu_massCAT4130 = new_mu_massCAT5130 = -1;
    old_mu_tree130->GetEntry(i);
    new_mu_mass130 = old_mu_mass130;
    new_mu_weight130 = old_mu_weight130*old_mu_weightPU130;
    new_mu_lumi130 = old_mu_nevt130;
    if (old_mu_cat130 == 21 && old_mu_jet130 == -1){
      new_mu_massCAT1130 = old_mu_mass130;
    }else if (old_mu_cat130 == 22 && old_mu_jet130 == -1){
      new_mu_massCAT4130 = old_mu_mass130;
    }else if ((old_mu_cat130 == 23 || old_mu_cat130 == 24) && old_mu_jet130 == -1){
      new_mu_massCAT3130 = old_mu_mass130;
    }else if ((old_mu_cat130 == 25 || old_mu_cat130 == 26) && old_mu_jet130 == -1){
      new_mu_massCAT2130 = old_mu_mass130;
    }else if (old_mu_jet130 == 1){
      new_mu_massCAT5130 = old_mu_mass130;
    }

    new_mu_tree130->Fill();
  }

  for( int i=0; i<old_mu_tree135->GetEntries(); i++ ) {
    new_mu_mass135 = new_mu_massCAT1135 = new_mu_massCAT2135 = new_mu_massCAT3135 = new_mu_massCAT4135 = new_mu_massCAT5135 = -1;
    old_mu_tree135->GetEntry(i);
    new_mu_mass135 = old_mu_mass135;
    new_mu_weight135 = old_mu_weight135*old_mu_weightPU135;
    new_mu_lumi135 = old_mu_nevt135;
    if (old_mu_cat135 == 21 && old_mu_jet135 == -1){
      new_mu_massCAT1135 = old_mu_mass135;
    }else if (old_mu_cat135 == 22 && old_mu_jet135 == -1){
      new_mu_massCAT4135 = old_mu_mass135;
    }else if ((old_mu_cat135 == 23 || old_mu_cat135 == 24) && old_mu_jet135 == -1){
      new_mu_massCAT3135 = old_mu_mass135;
    }else if ((old_mu_cat135 == 25 || old_mu_cat135 == 26) && old_mu_jet135 == -1){
      new_mu_massCAT2135 = old_mu_mass135;
    }else if (old_mu_jet135 == 1){
      new_mu_massCAT5135 = old_mu_mass135;
    }

    new_mu_tree135->Fill();
  }
  
  for( int i=0; i<old_mu_tree140->GetEntries(); i++ ) {
    new_mu_mass140 = new_mu_massCAT1140 = new_mu_massCAT2140 = new_mu_massCAT3140 = new_mu_massCAT4140 = new_mu_massCAT5140 = -1;
    old_mu_tree140->GetEntry(i);
    new_mu_mass140 = old_mu_mass140;
    new_mu_weight140 = old_mu_weight140*old_mu_weightPU140;
    new_mu_lumi140 = old_mu_nevt140;
    if (old_mu_cat140 == 21 && old_mu_jet140 == -1){
      new_mu_massCAT1140 = old_mu_mass140;
    }else if (old_mu_cat140 == 22 && old_mu_jet140 == -1){
      new_mu_massCAT4140 = old_mu_mass140;
    }else if ((old_mu_cat140 == 23 || old_mu_cat140 == 24) && old_mu_jet140 == -1){
      new_mu_massCAT3140 = old_mu_mass140;
    }else if ((old_mu_cat140 == 25 || old_mu_cat140 == 26) && old_mu_jet140 == -1){
      new_mu_massCAT2140 = old_mu_mass140;
    }else if (old_mu_jet140 == 1){
      new_mu_massCAT5140 = old_mu_mass140;
    }

    new_mu_tree140->Fill();
  }

  for( int i=0; i<old_mu_tree145->GetEntries(); i++ ) {
    new_mu_mass145 = new_mu_massCAT1145 = new_mu_massCAT2145 = new_mu_massCAT3145 = new_mu_massCAT4145 = new_mu_massCAT5145 = -1;
    old_mu_tree145->GetEntry(i);
    new_mu_mass145 = old_mu_mass145;
    new_mu_weight145 = old_mu_weight145*old_mu_weightPU145;
    new_mu_lumi145 = old_mu_nevt145;
    if (old_mu_cat145 == 21 && old_mu_jet145 == -1){
      new_mu_massCAT1145 = old_mu_mass145;
    }else if (old_mu_cat145 == 22 && old_mu_jet145 == -1){
      new_mu_massCAT4145 = old_mu_mass145;
    }else if ((old_mu_cat145 == 23 || old_mu_cat145 == 24) && old_mu_jet145 == -1){
      new_mu_massCAT3145 = old_mu_mass145;
    }else if ((old_mu_cat145 == 25 || old_mu_cat145 == 26) && old_mu_jet145 == -1){
      new_mu_massCAT2145 = old_mu_mass145;
    }else if (old_mu_jet145 == 1){
      new_mu_massCAT5145 = old_mu_mass145;
    }

    new_mu_tree145->Fill();
  }

  for( int i=0; i<old_mu_tree150->GetEntries(); i++ ) {
    new_mu_mass150 = new_mu_massCAT1150 = new_mu_massCAT2150 = new_mu_massCAT3150 = new_mu_massCAT4150 = new_mu_massCAT5150 = -1;
    old_mu_tree150->GetEntry(i);
    new_mu_mass150 = old_mu_mass150;
    new_mu_weight150 = old_mu_weight150*old_mu_weightPU150;
    new_mu_lumi150 = old_mu_nevt150;
    if (old_mu_cat150 == 21 && old_mu_jet150 == -1){
      new_mu_massCAT1150 = old_mu_mass150;
    }else if (old_mu_cat150 == 22 && old_mu_jet150 == -1){
      new_mu_massCAT4150 = old_mu_mass150;
    }else if ((old_mu_cat150 == 23 || old_mu_cat150 == 24) && old_mu_jet150 == -1){
      new_mu_massCAT3150 = old_mu_mass150;
    }else if ((old_mu_cat150 == 25 || old_mu_cat150 == 26) && old_mu_jet150 == -1){
      new_mu_massCAT2150 = old_mu_mass150;
    }else if (old_mu_jet150 == 1){
      new_mu_massCAT5150 = old_mu_mass150;
    }

    new_mu_tree150->Fill();
  }

  for( int i=0; i<old_mu_tree155->GetEntries(); i++ ) {
    new_mu_mass155 = new_mu_massCAT1155 = new_mu_massCAT2155 = new_mu_massCAT3155 = new_mu_massCAT4155 = new_mu_massCAT5155 = -1;
    old_mu_tree155->GetEntry(i);
    new_mu_mass155 = old_mu_mass155;
    new_mu_weight155 = old_mu_weight155*old_mu_weightPU155;
    new_mu_lumi155 = old_mu_nevt155;
    if (old_mu_cat155 == 21 && old_mu_jet155 == -1){
      new_mu_massCAT1155 = old_mu_mass155;
    }else if (old_mu_cat155 == 22 && old_mu_jet155 == -1){
      new_mu_massCAT4155 = old_mu_mass155;
    }else if ((old_mu_cat155 == 23 || old_mu_cat155 == 24) && old_mu_jet155 == -1){
      new_mu_massCAT3155 = old_mu_mass155;
    }else if ((old_mu_cat155 == 25 || old_mu_cat155 == 26) && old_mu_jet155 == -1){
      new_mu_massCAT2155 = old_mu_mass155;
    }else if (old_mu_jet155 == 1){
      new_mu_massCAT5155 = old_mu_mass155;
    }

    new_mu_tree155->Fill();
  }

  for( int i=0; i<old_mu_tree160->GetEntries(); i++ ) {
    new_mu_mass160 = new_mu_massCAT1160 = new_mu_massCAT2160 = new_mu_massCAT3160 = new_mu_massCAT4160 = new_mu_massCAT5160 = -1;
    old_mu_tree160->GetEntry(i);
    new_mu_mass160 = old_mu_mass160;
    new_mu_weight160 = old_mu_weight160*old_mu_weightPU160;
    new_mu_lumi160 = old_mu_nevt160;
    if (old_mu_cat160 == 21 && old_mu_jet160 == -1){
      new_mu_massCAT1160 = old_mu_mass160;
    }else if (old_mu_cat160 == 22 && old_mu_jet160 == -1){
      new_mu_massCAT4160 = old_mu_mass160;
    }else if ((old_mu_cat160 == 23 || old_mu_cat160 == 24) && old_mu_jet160 == -1){
      new_mu_massCAT3160 = old_mu_mass160;
    }else if ((old_mu_cat160 == 25 || old_mu_cat160 == 26) && old_mu_jet160 == -1){
      new_mu_massCAT2160 = old_mu_mass160;
    }else if (old_mu_jet160 == 1){
      new_mu_massCAT5160 = old_mu_mass160;
    }

    new_mu_tree160->Fill();
  }


  new_mu_tree120->Print();
  new_mu_tree125->Print();
  new_mu_tree130->Print();
  new_mu_tree135->Print();
  new_mu_tree140->Print();
  new_mu_tree145->Print();
  new_mu_tree150->Print();
  new_mu_tree155->Print();
  new_mu_tree160->Print();
  new_mu_file->Write();
  delete old_mu_file120;
  delete old_mu_file125;
  delete old_mu_file130;
  delete old_mu_file135;
  delete old_mu_file140;
  delete old_mu_file145;
  delete old_mu_file150;
  delete old_mu_file155;
  delete old_mu_file160;
  delete new_mu_file;
}
