void copyTreeData() {
  // Example of Root macro to copy a subset of a Tree to a new Tree
  // One branch of the new Tree is written to a separate file
  // The input file has been generated by the program in $ROOTSYS/test/Event
  // with   Event 1000 1 1 1
  //Author: Rene Brun

  //Get old file, old tree and set top branch address
  //TFile *oldfileMu2012 = new TFile("/afs/cern.ch/user/p/poter/public/HZgamma_MiniTree/2012/Data_Zmumugamma_ScalingPhoPt15GeV_Medium_MuEnScale_PhoEnScale_NoHLTMatching_VBFTag/Data_Zmumugamma_m190GeV.root");
  //TFile *oldfileEl2012 = new TFile("/afs/cern.ch/user/p/poter/public/HZgamma_MiniTree/2012/Data_Zeegamma_ScalingPhoPt15GeV_Medium_EleEnScale_PhoEnScale_NoHLTMatching_VBFTag/Data_Zeegamma_m190GeV.root");
  //TFile *oldfileMu2011 = new TFile("/afs/cern.ch/user/p/poter/public/HZgamma_MiniTree/2011/Data_Zmumugamma_ScalingPhoPt15GeV_Medium_MuEnScale_PhoEnScale_NoHLTMatching_VBFTag/Data_Zmumugamma_m190GeV.root");
  //TFile *oldfileEl2011 = new TFile("/afs/cern.ch/user/p/poter/public/HZgamma_MiniTree/2011/Data_Zeegamma_ScalingPhoPt15GeV_Medium_EleEnScale_PhoEnScale_NoHLTMatching_VBFTag/Data_Zeegamma_m190GeV.root");

  TFile *oldfileMu2012 = new TFile("poterData_mu_8TeV.root");
  TFile *oldfileEl2012 = new TFile("poterData_el_8TeV.root");
  TFile *oldfileMu2011 = new TFile("poterData_mu_7TeV.root");
  TFile *oldfileEl2011 = new TFile("poterData_el_7TeV.root");

  TTree *oldtreeMu2012 = (TTree*)oldfileMu2012->Get("DataTree");
  TTree *oldtreeEl2012 = (TTree*)oldfileEl2012->Get("DataTree");
  TTree *oldtreeMu2011 = (TTree*)oldfileMu2011->Get("DataTree");
  TTree *oldtreeEl2011 = (TTree*)oldfileEl2011->Get("DataTree");

  double oldmassMu2012,oldmassMu2011,oldmassEl2012,oldmassEl2011;
  double oldcatMu2012,oldcatMu2011,oldcatEl2012,oldcatEl2011;
  double oldjetMu2012,oldjetMu2011,oldjetEl2012,oldjetEl2011;

  double newmassMu2012,newmassMu2011,newmassEl2012,newmassEl2011,newmassAll2011;
  double newmassCAT1Mu2012,newmassCAT1Mu2011,newmassCAT1El2012,newmassCAT1El2011, newmassCAT1All2011;
  double newmassCAT2Mu2012,newmassCAT2Mu2011,newmassCAT2El2012,newmassCAT2El2011, newmassCAT2All2011;
  double newmassCAT3Mu2012,newmassCAT3Mu2011,newmassCAT3El2012,newmassCAT3El2011, newmassCAT3All2011;
  double newmassCAT4Mu2012,newmassCAT4Mu2011,newmassCAT4El2012,newmassCAT4El2011, newmassCAT4All2011;
  double newmassCAT5Mu2012,newmassCAT5Mu2011,newmassCAT5El2012,newmassCAT5El2011, newmassCAT5All2011;

  oldtreeMu2012->SetBranchAddress("mass",&oldmassMu2012);
  oldtreeEl2012->SetBranchAddress("mass",&oldmassEl2012);
  oldtreeMu2011->SetBranchAddress("mass",&oldmassMu2011);
  oldtreeEl2011->SetBranchAddress("mass",&oldmassEl2011);
  oldtreeMu2012->SetBranchAddress("cat1",&oldcatMu2012);
  oldtreeEl2012->SetBranchAddress("cat1",&oldcatEl2012);
  oldtreeMu2011->SetBranchAddress("cat1",&oldcatMu2011);
  oldtreeEl2011->SetBranchAddress("cat1",&oldcatEl2011);
  oldtreeMu2012->SetBranchAddress("jettag",&oldjetMu2012);
  oldtreeEl2012->SetBranchAddress("jettag",&oldjetEl2012);
  oldtreeMu2011->SetBranchAddress("jettag",&oldjetMu2011);
  oldtreeEl2011->SetBranchAddress("jettag",&oldjetEl2011);


  TFile *newfileMu2012 = new TFile("data_Mu2012.root","recreate");
  TTree *newtreeMu2012 = new TTree("m_llg_DATA","m_llg_DATA");
  newtreeMu2012->Branch("m_llg_DATA",&newmassMu2012);
  newtreeMu2012->Branch("m_llgCAT1_DATA",&newmassCAT1Mu2012);
  newtreeMu2012->Branch("m_llgCAT2_DATA",&newmassCAT2Mu2012);
  newtreeMu2012->Branch("m_llgCAT3_DATA",&newmassCAT3Mu2012);
  newtreeMu2012->Branch("m_llgCAT4_DATA",&newmassCAT4Mu2012);
  newtreeMu2012->Branch("m_llgCAT5_DATA",&newmassCAT5Mu2012);

  TFile *newfileMu2011 = new TFile("data_Mu2011.root","recreate");
  TTree *newtreeMu2011 = new TTree("m_llg_DATA","m_llg_DATA");
  newtreeMu2011->Branch("m_llg_DATA",&newmassMu2011);
  newtreeMu2011->Branch("m_llgCAT1_DATA",&newmassCAT1Mu2011);
  newtreeMu2011->Branch("m_llgCAT2_DATA",&newmassCAT2Mu2011);
  newtreeMu2011->Branch("m_llgCAT3_DATA",&newmassCAT3Mu2011);
  newtreeMu2011->Branch("m_llgCAT4_DATA",&newmassCAT4Mu2011);
  newtreeMu2011->Branch("m_llgCAT5_DATA",&newmassCAT5Mu2011);

  TFile *newfileEl2012 = new TFile("data_El2012.root","recreate");
  TTree *newtreeEl2012 = new TTree("m_llg_DATA","m_llg_DATA");
  newtreeEl2012->Branch("m_llg_DATA",&newmassEl2012);
  newtreeEl2012->Branch("m_llgCAT1_DATA",&newmassCAT1El2012);
  newtreeEl2012->Branch("m_llgCAT2_DATA",&newmassCAT2El2012);
  newtreeEl2012->Branch("m_llgCAT3_DATA",&newmassCAT3El2012);
  newtreeEl2012->Branch("m_llgCAT4_DATA",&newmassCAT4El2012);
  newtreeEl2012->Branch("m_llgCAT5_DATA",&newmassCAT5El2012);

  TFile *newfileEl2011 = new TFile("data_El2011.root","recreate");
  TTree *newtreeEl2011 = new TTree("m_llg_DATA","m_llg_DATA");
  newtreeEl2011->Branch("m_llg_DATA",&newmassEl2011);
  newtreeEl2011->Branch("m_llgCAT1_DATA",&newmassCAT1El2011);
  newtreeEl2011->Branch("m_llgCAT2_DATA",&newmassCAT2El2011);
  newtreeEl2011->Branch("m_llgCAT3_DATA",&newmassCAT3El2011);
  newtreeEl2011->Branch("m_llgCAT4_DATA",&newmassCAT4El2011);
  newtreeEl2011->Branch("m_llgCAT5_DATA",&newmassCAT5El2011);

  TFile *newfileAll2011 = new TFile("data_All2011.root","recreate");
  TTree *newtreeAll2011 = new TTree("m_llg_DATA","m_llg_DATA");
  newtreeAll2011->Branch("m_llg_DATA",&newmassAll2011);
  newtreeAll2011->Branch("m_llgCAT1_DATA",&newmassCAT1All2011);
  newtreeAll2011->Branch("m_llgCAT2_DATA",&newmassCAT2All2011);
  newtreeAll2011->Branch("m_llgCAT3_DATA",&newmassCAT3All2011);
  newtreeAll2011->Branch("m_llgCAT4_DATA",&newmassCAT4All2011);
  newtreeAll2011->Branch("m_llgCAT5_DATA",&newmassCAT5All2011);

  for( int i=0; i<oldtreeMu2012->GetEntries(); i++ ) {
    newmassMu2012 = newmassCAT1Mu2012 = newmassCAT2Mu2012 = newmassCAT3Mu2012 = newmassCAT4Mu2012 = newmassCAT5Mu2012 = -1;
    oldtreeMu2012->GetEntry(i);
    newmassMu2012 = oldmassMu2012;
    if (oldcatMu2012 == 21 && oldjetMu2012 == -1){
      newmassCAT1Mu2012 = oldmassMu2012;
    }else if (oldcatMu2012 == 22 && oldjetMu2012 == -1){
      newmassCAT4Mu2012 = oldmassMu2012;
    }else if ((oldcatMu2012 == 25 || oldcatMu2012 == 26) && oldjetMu2012 == -1){
      newmassCAT2Mu2012 = oldmassMu2012;
    }else if ((oldcatMu2012 == 23 || oldcatMu2012 == 24) && oldjetMu2012 == -1){
      newmassCAT3Mu2012 = oldmassMu2012;
    }else if (oldjetMu2012 == 1){
      newmassCAT5Mu2012 = oldmassMu2012;
    }

    newtreeMu2012->Fill();
  }
  for( int i=0; i<oldtreeMu2011->GetEntries(); i++ ) {
    newmassMu2011 = newmassCAT1Mu2011 = newmassCAT2Mu2011 = newmassCAT3Mu2011 = newmassCAT4Mu2011 = newmassCAT5Mu2011 = -1;
    newmassAll2011 = newmassCAT1All2011 = newmassCAT2All2011 = newmassCAT3All2011 = newmassCAT4All2011 = newmassCAT5All2011 = -1;
    oldtreeMu2011->GetEntry(i);
    newmassMu2011 = oldmassMu2011;
    newmassAll2011 = oldmassMu2011;
    if (oldcatMu2011 == 21 && oldjetMu2011 == -1){
      newmassCAT1Mu2011 = oldmassMu2011;
      newmassCAT1All2011 = oldmassMu2011;
    }else if (oldcatMu2011 == 22 && oldjetMu2011 == -1){
      newmassCAT4Mu2011 = oldmassMu2011;
      newmassCAT4All2011 = oldmassMu2011;
    }else if ((oldcatMu2011 == 25 || oldcatMu2011 == 26) && oldjetMu2011 == -1){
      newmassCAT2Mu2011 = oldmassMu2011;
      newmassCAT2All2011 = oldmassMu2011;
    }else if ((oldcatMu2011 == 23 || oldcatMu2011 == 24) && oldjetMu2011 == -1){
      newmassCAT3Mu2011 = oldmassMu2011;
      newmassCAT3All2011 = oldmassMu2011;
    }else if (oldjetMu2011 == 1){
      newmassCAT5Mu2011 = oldmassMu2011;
      newmassCAT5All2011 = oldmassMu2011;
    }

    newtreeMu2011->Fill();
    newtreeAll2011->Fill();
  }
  for( int i=0; i<oldtreeEl2012->GetEntries(); i++ ) {
    newmassEl2012 = newmassCAT1El2012 = newmassCAT2El2012 = newmassCAT3El2012 = newmassCAT4El2012 = newmassCAT5El2012 = -1;
    oldtreeEl2012->GetEntry(i);
    newmassEl2012 = oldmassEl2012;
    if (oldcatEl2012 == 11 && oldjetEl2012 == -1){
      newmassCAT1El2012 = oldmassEl2012;
    }else if (oldcatEl2012 == 12 && oldjetEl2012 == -1){
      newmassCAT4El2012 = oldmassEl2012;
    }else if ((oldcatEl2012 == 15 || oldcatEl2012 == 16) && oldjetEl2012 == -1){
      newmassCAT2El2012 = oldmassEl2012;
    }else if ((oldcatEl2012 == 13 || oldcatEl2012 == 14) && oldjetEl2012 == -1){
      newmassCAT3El2012 = oldmassEl2012;
    }else if (oldjetEl2012 == 1){
      newmassCAT5El2012 = oldmassEl2012;
    }

    newtreeEl2012->Fill();
  }
  for( int i=0; i<oldtreeEl2011->GetEntries(); i++ ) {
    newmassEl2011 = newmassCAT1El2011 = newmassCAT2El2011 = newmassCAT3El2011 = newmassCAT4El2011 = newmassCAT5El2011 = -1;
    newmassAll2011 = newmassCAT1All2011 = newmassCAT2All2011 = newmassCAT3All2011 = newmassCAT4All2011 = newmassCAT5All2011 = -1;
    oldtreeEl2011->GetEntry(i);
    newmassEl2011 = oldmassEl2011;
    newmassAll2011 = oldmassEl2011;
    if (oldcatEl2011 == 11 && oldjetEl2011 == -1){
      newmassCAT1El2011 = oldmassEl2011;
      newmassCAT1All2011 = oldmassEl2011;
    }else if (oldcatEl2011 == 12 && oldjetEl2011 == -1){
      newmassCAT4El2011 = oldmassEl2011;
      newmassCAT4All2011 = oldmassEl2011;
    }else if ((oldcatEl2011 == 15 || oldcatEl2011 == 16) && oldjetEl2011 == -1){
      newmassCAT2El2011 = oldmassEl2011;
      newmassCAT2All2011 = oldmassEl2011;
    }else if ((oldcatEl2011 == 13 || oldcatEl2011 == 14) && oldjetEl2011 == -1){
      newmassCAT3El2011 = oldmassEl2011;
      newmassCAT3All2011 = oldmassEl2011;
    }else if (oldjetEl2011 == 1){
      newmassCAT5El2011 = oldmassEl2011;
      newmassCAT5All2011 = oldmassEl2011;
    }

    newtreeEl2011->Fill();
    newtreeAll2011->Fill();
  }

  newtreeMu2012->Print();
  newfileMu2012->Write();
  newtreeMu2011->Print();
  newfileMu2011->Write();
  newtreeEl2012->Print();
  newfileEl2012->Write();
  newtreeEl2011->Print();
  newfileEl2011->Write();
  newtreeAll2011->Print();
  newfileAll2011->Write();
  delete oldfileMu2012;
  delete oldfileMu2011;
  delete oldfileEl2012;
  delete oldfileEl2011;
  delete newfileMu2012;
  delete newfileMu2011;
  delete newfileEl2012;
  delete newfileEl2011;
  delete newfileAll2011;
}
